version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - cd website
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on 'date'
      - npm run build
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id EWAHHVHF75WWZ --paths "/*"

artifacts:
  files:
    - '**/*'
    #- "website/build/**/*"
  base-directory: 'website/build'
  #discard-paths: yes